name: Node.js CI

on: push

jobs:
  buildAndTest:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_READ_TOKEN}}
      - run: npm run lint
      - run: npm run build:asm
      - run: npm run test
      - run: npm run test:asm
      - name: Upload asm.js
        uses: actions/upload-artifact@v3
        with:
          name: asm
          path: asm.js

  publish:
    needs: buildAndTest
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Download asm.js
        uses: actions/download-artifact@v3
        with:
          name: asm
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_READ_TOKEN}}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
